/*
 * Copyright (c) 2022 Maximilian Bauer
 * Distributed under the GNU GPL v3. For full terms see the file "COPYING".
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowOne.Resources
{
    
    internal partial class WebResources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((WebResources.manager == null))
                {
                    WebResources.manager = new System.Resources.ResourceManager("GrowOne.Resources.WebResources", typeof(WebResources).Assembly);
                }
                return WebResources.manager;
            }
        }
        internal static byte[] GetBytes(WebResources.BinaryResources id)
        {
            return ((byte[])(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            index_html = 13751,
            logo = 17715,
        }
    }
}
